# Python 中的例外處理

<br>

## 成員

1. try
2. except
3. finally
4. else
5. raise


<br>

## 各種組合

1. try + except，最基本的結構。
2. 有多個 except。
3. try + except + finally。
4. raise，自主觸發的例外。
5. try + except + else + finally，完全捕捉的例外處理。


<br>

## 詳細說明

### 1. 基礎結構：try + except
   
#### 說明

1. 將可能會引發錯誤的代碼塊放在 `try` 語句中，然後在 `except` 語句中處理特定的 `錯誤` (或稱 `異常` ) 。

#### 範例

1. ZeroDivisionError：除法中的除數為 0

    ```python
    try:
        # 嘗試執行的程式碼
        x = 1 / 0
    except ZeroDivisionError:
        # 當發生 ZeroDivisionError 時執行的程式碼
        print("除數不可為 0")
    ```
    _RESULT_
    ```bash
    除數不可為 0
    ```

<br>

---

### 2. 有多個 except

#### 說明

1. 可以在一個 try 語句中包含多個 except 語句來捕捉和處理不同的錯誤類型。

2. 如果不確定可能會發生什麼錯誤，也可以捕捉所有的例外

<br>

#### 範例 
   
1. ZeroDivisionError：除法中的除數為 0。

    ```python
    try:
        # 嘗試執行的程式碼
        x = 1 / 0
           
    except TypeError:
        # 當 TypeError 異常發生時執行的程式碼
        print(TypeError)
           
    except ValueError:
        # 當 ValueError 異常發生時執行的程式碼
        print(ValueError)
           
    # 捕捉其他全部例外
    except:
        print("其他例外")    
    ```
    _RESULT_
    ```bash
    其他例外
    ```

   <br>

2. TypeError：嘗試對某個值進行 `不支援的操作` 時引發的異常。

   - 舉例說，如果嘗試將一個整數與一個字串相加，Python 就會引發 `TypeError` 。

    ```python
    try:
        # 嘗試執行的程式碼
        x = 5 + 'hello'
           
    except TypeError:
        # 當 TypeError 異常發生時執行的程式碼
        print(TypeError)
           
    except ValueError:
        # 當 ValueError 異常發生時執行的程式碼
        print(ValueError)
           
    # 捕捉其他全部例外
    except:
        print("其他例外")       
    ```
    _RESULT_
    ```bash
    <class 'TypeError'>
    ```

   <br>

3. ValueError：嘗試對一個函數提供一個可處理類型、但是實際值不合法的參救時會引發的異常。

   - 例如，Python 可以將字串轉換為整數，但若嘗傳入的字串並非數字表示的字串，此時會引發 ValueError。

    ```python
    try:
        # 嘗試執行的程式碼
        x = int('hello')
           
    except TypeError:
        # 當 TypeError 異常發生時執行的程式碼
        print(TypeError)
           
    except ValueError:
        # 當 ValueError 異常發生時執行的程式碼
        print(ValueError)
           
    # 捕捉其他全部例外
    except:
        print("其他例外")
    ```
    _OUTPUT_
    ```bash
    <class 'ValueError'>
    ```

<br>

---

### 3. try + except + finally

#### 說明   

1. 用 `finally` 語句來添加一個 `程式碼區塊 block`，無論是否發生錯誤，該區塊最後都會執行。

#### 範例

1. 除數為 0

    ```python
    try:
        # 嘗試執行的程式碼
        x = 1 / 0
    except ZeroDivisionError:
        # 當發生 ZeroDivisionError 時執行的程式碼
        print("除數不可為零")
    finally:
        # 無論是否發生錯誤都會執行的程式碼
        print("無論是否發生錯誤，完成例外處理時都會執行此區塊")
    ```
    _RESULT_
    ```bash
    除數不可為零
    完成這個例外處理程式碼
    ```

<br>

---

### 4. raise

#### 說明

1. 主動觸發錯誤
2. 使用 raise 可 `主動觸發` 一個特定的錯誤或例外。

#### 範例

    ```python
    try:
        raise ValueError("發生錯誤了!")
    except ValueError as e:
        print(f"捕捉到錯誤：{e}")
    ```
    _OUTPUT_
    ```bash
    捕捉到錯誤：發生錯誤了!
    ```

<br>

---

### 5. try + except + else + finally

#### 說明

1. 當沒發生錯誤時，除了 try 本身以外，還會執行 else 區塊。

#### 範例

1. 沒發生錯誤

    ```python
    try:
        # 嘗試執行的程式碼
        x = 1 / 2
    except Exception:
        # 當發生任何錯誤時執行的程式碼
        print("發生錯誤了!")
    else:
        # 當沒有發生錯誤時執行的程式碼
        print(f"沒有發生錯誤時，其他要做的事，比如說輸出結果：{x}")
        
    finally:
        # 無論是否發生錯誤都會執行的程式碼
        print("無論是否發生錯誤，完成例外處理時都會執行此區塊")

    ```
    _OUTPUT_
    ```bash
    沒有發生錯誤時，其他要做的事，比如說輸出結果：0.5
    無論是否發生錯誤，完成例外處理時都會執行此區塊
    ```

<br>

---

_END_